// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj9HlajT0By1JifA7vwZz8gPBUkgeXOYQ',
    appId: '1:765660360365:android:5951e66640fb8907ae6024',
    messagingSenderId: '765660360365',
    projectId: 'drowsydriver-eff03',
    databaseURL: 'https://drowsydriver-eff03-default-rtdb.firebaseio.com',
    storageBucket: 'drowsydriver-eff03.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9HlajT0By1JifA7vwZz8gPBUkgeXOYQ',
    appId: '1:765660360365:android:5951e66640fb8907ae6024',
    messagingSenderId: '765660360365',
    projectId: 'drowsydriver-eff03',
    databaseURL: 'https://drowsydriver-eff03-default-rtdb.firebaseio.com',
    storageBucket: 'drowsydriver-eff03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9HlajT0By1JifA7vwZz8gPBUkgeXOYQ',
    appId: '1:765660360365:ios:placeholder',
    messagingSenderId: '765660360365',
    projectId: 'drowsydriver-eff03',
    databaseURL: 'https://drowsydriver-eff03-default-rtdb.firebaseio.com',
    storageBucket: 'drowsydriver-eff03.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.drowsydriver.app',
  );
}
