import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:url_launcher/url_launcher.dart';

// Ensure this file was generated by 'flutterfire configure'
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options (Required for Web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const DrowsyDashboardApp());
}

class DrowsyDashboardApp extends StatelessWidget {
  const DrowsyDashboardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Driver Monitoring System',
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF121212),
        primaryColor: Colors.orange,
      ),
      home: const DashboardScreen(),
    );
  }
}

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  _DashboardScreenState createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  final _dbRef = FirebaseDatabase.instance.ref();

  // State variables with default values to prevent null errors
  String _currentStatus = "SAFE";
  String _lastAlertImage = "";
  List<Map<dynamic, dynamic>> _alertHistory = [];

  @override
  void initState() {
    super.initState();
    _setupListeners();
  }

  void _setupListeners() {
    // 1. Listen for Real-time Status updates
    _dbRef.child('driver_status').onValue.listen((event) {
      if (event.snapshot.value != null) {
        final data = Map<dynamic, dynamic>.from(event.snapshot.value as Map);
        setState(() {
          _currentStatus = data['status']?.toString() ?? "SAFE";
          _lastAlertImage = data['last_alert_image']?.toString() ?? "";
        });
      }
    });

    // 2. Listen for Historical Logs with Robust Error Handling
    _dbRef.child('alerts_history').onValue.listen((event) {
      if (event.snapshot.value != null) {
        final Map<dynamic, dynamic> values = event.snapshot.value as Map;
        List<Map<dynamic, dynamic>> tempList = [];

        values.forEach((key, value) {
          if (value is Map) {
            tempList.add(Map<dynamic, dynamic>.from(value));
          }
        });

        // Sort by timestamp descending (Newest first)
        tempList.sort((a, b) {
          String aTime = a['timestamp']?.toString() ?? "";
          String bTime = b['timestamp']?.toString() ?? "";
          return bTime.compareTo(aTime);
        });

        setState(() {
          _alertHistory = tempList;
        });
      }
    });
  }

  // Helper to safely open Cloudinary URLs
  Future<void> _launchCloudinaryUrl(String? url) async {
    if (url == null || url.isEmpty) return;
    final Uri uri = Uri.parse(url);
    if (!await launchUrl(uri, mode: LaunchMode.externalApplication)) {
      debugPrint("Could not launch $url");
    }
  }

  @override
  Widget build(BuildContext context) {
    bool isDanger = _currentStatus == "DANGER";

    return Scaffold(
      appBar: AppBar(
        title: const Text("IoT Driver Safety Dashboard"),
        centerTitle: true,
        backgroundColor: Colors.black,
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            const SizedBox(height: 15),
            const Text(
              "System Health: ACTIVE",
              style: TextStyle(
                  color: Colors.green,
                  fontWeight: FontWeight.bold,
                  fontSize: 12),
            ),

            // Dynamic Status Badge
            Padding(
              padding: const EdgeInsets.all(20.0),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 500),
                width: double.infinity,
                padding: const EdgeInsets.all(30),
                decoration: BoxDecoration(
                  color: isDanger ? Colors.red : Colors.greenAccent.shade700,
                  borderRadius: BorderRadius.circular(15),
                  boxShadow: [
                    BoxShadow(
                      color:
                          isDanger ? Colors.red.withOpacity(0.4) : Colors.black,
                      blurRadius: 10,
                    )
                  ],
                ),
                child: Column(
                  children: [
                    Text(
                      isDanger ? "DROWSINESS DETECTED" : "DRIVER STATUS: SAFE",
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Colors.white),
                    ),
                  ],
                ),
              ),
            ),

            const Text("Latest Evidence Capture",
                style: TextStyle(
                    fontWeight: FontWeight.bold, color: Colors.orange)),

            // Latest Image with Placeholder
            Padding(
              padding: const EdgeInsets.all(15.0),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(10),
                child: _lastAlertImage.isNotEmpty
                    ? CachedNetworkImage(
                        imageUrl: _lastAlertImage,
                        height: 200,
                        width: double.infinity,
                        fit: BoxFit.cover,
                        placeholder: (context, url) =>
                            const Center(child: CircularProgressIndicator()),
                        errorWidget: (context, url, error) =>
                            const Icon(Icons.warning, size: 50),
                      )
                    : Container(
                        height: 200,
                        color: Colors.grey[900],
                        child: const Icon(Icons.camera_alt,
                            size: 50, color: Colors.grey)),
              ),
            ),

            const Padding(
              padding: EdgeInsets.symmetric(vertical: 10),
              child: Text("Historical Alert Log",
                  style: TextStyle(
                      fontWeight: FontWeight.bold, color: Colors.orange)),
            ),

            // Historical Table with Range-Error Protections
            Padding(
              padding: const EdgeInsets.only(bottom: 40),
              child: SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: DataTable(
                  columns: const [
                    DataColumn(label: Text("Timestamp")),
                    DataColumn(label: Text("EAR")),
                    DataColumn(label: Text("View")),
                  ],
                  rows: _alertHistory.map((alert) {
                    // SAFE TIMESTAMP PARSING TO PREVENT RANGE ERRORS
                    String rawTS = alert['timestamp']?.toString() ?? "00:00:00";
                    String displayTime = "N/A";
                    try {
                      if (rawTS.contains(' ')) {
                        displayTime = rawTS.split(' ')[1];
                        if (displayTime.length > 8)
                          displayTime = displayTime.substring(0, 8);
                      } else {
                        displayTime =
                            rawTS.length > 10 ? rawTS.substring(0, 10) : rawTS;
                      }
                    } catch (_) {
                      displayTime = "Fixing...";
                    }

                    return DataRow(cells: [
                      DataCell(Text(displayTime)),
                      DataCell(Text(alert['ear']?.toString() ?? "0.0")),
                      DataCell(
                        IconButton(
                          icon: const Icon(Icons.open_in_new,
                              color: Colors.blue, size: 18),
                          onPressed: () => _launchCloudinaryUrl(
                              alert['image_url']?.toString()),
                        ),
                      ),
                    ]);
                  }).toList(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
